version: '3.1'

services:
  herodotus-database:
    container_name: herodotus-database
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: herodotus_logs